
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/nix/store/ih3wsahlr3d787jc4kzqizp6syq6hy29-cmake-3.29.3/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:4 (project)"
    message: |
      The system is: Linux - 6.9.3-zen1 - x86_64
...
